# Generated by Django 4.2.5 on 2023-10-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiFuse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='apk_file',
            new_name='apk_file_name',
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='file_name',
        ),
    ]
